### PR TITLE
lookbehind fix?

### PR DESCRIPTION
**Pull request by larshp**
https://github.com/pvl/abap.tmbundle/issues/79

split into two fixed width expressions

however, I dont remember how to test the grammar, hmm

### CODE REVIEW

**Comment by FreHu** [comment]
There was a test app, but it was deprecated
https://github.com/github/linguist/issues/5844

**Comment by mbtools** [comment]
Two `/` after the `a-z` need to be escaped but then it should work:

https://regex101.com/r/1b5b8w/1

`(?i)(?<=(?:\s|~|-))(?<=(?:->|=>))([a-z_\/][a-z_0-9\/]*)(?=\s+(?:=|\+=|-=|\*=|\/=|&&=)\s+)`

**Comment by mbtools** [comment]
Here's what the change should look like:

```xml
			<dict>
				<key>match</key>
				<string>(?i)(?<=(?:\s|~|-))(?&lt;=(?:-&gt;|=&gt;))([a-z_\/][a-z_0-9\/]*)(?=\s+(?:=|\+=|-=|\*=|\/=|&amp;&amp;=)\s+)</string>
				<key>name</key>
				<string>variable.other.abap</string>
			</dict>
```

I tested it at https://novalightshow.netlify.app/.

**Comment by larshp** [comment]
close this PR and open a new?

**Comment by mbtools** [comment]
sure but i'm not authorized here

**Pull request closed without merging**
